# SELF PLAY
MAX_MOVES = 280
ROOT_DIRICHLET_ALPHA = 0.8
ROOT_DIRICHLET_WEIGHT = 0.25
TURNS_UNTIL_TAU0 = 10
CPUCT = 4
SIMS_FAKTOR = 8
SIMS_EXPONENT = 1.15
EPISODES = 150
MIN_MEMORY = 200000
MAX_MEMORY = 600000
MEMORY_ITERS = 15

# RETRAINING

BATCH_SIZE = 256
EPOCHS = 12
KERNEL_SIZE = 3
FILTERS = 64
OUT_FILTERS = 24
OUT_KERNEL_SIZE = 1
HIDDEN_SIZE = 224
INPUT_SIZE = 8, 3, 4
NUM_ACTIONS = 76
NETWORK_PATH = "run4/models/episode-"
BEST_PATH = "run4/models/best_net.h5"
NEW_NET_PATH = "run4/models/new_net.h5"
TENSORBOARD_PATH = "run4/Tensorboard/episode-"

# EVAL

EVAL_EPISODES = 24
SCORING_THRESHOLD = 1.17

# GENERAL
NUM_CPUS = 12
TRAINING_LOOPS = 50
LOGGER_PATH = "run4/AlphaLog.log"
INTERMEDIATE_SAVE_PATH = "run4/"
